[theme]
base = "light"
primaryColor = "#F47920"
backgroundColor = "#F4F6FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B2B5E"
font = "sans serif"

[server]
headless = true
enableCORS = false
